# Generated by Django 2.2.7 on 2019-11-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemilu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='nim',
        ),
    ]
